use crate::{Core, for_tuples};

pub trait CoreExtract {
    fn extract(core: &mut Core) -> Self;
}

/// Implement for tuples of types that implement [`CoreExtract`].
#[macro_export]
macro_rules! impl_core_extract_tuple {
    ([$($ty:ident),+]) => {
        impl<$($ty: CoreExtract),+> CoreExtract for ($($ty,)+) {
            fn extract(core: &mut Core) -> Self {
                ($($ty::extract(core),)+)
            }
        }
    };
}

for_tuples!(
    impl_core_extract_tuple,
    prefix = [],
    extend = [
        T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15
    ]
);

/// Extend the implement for tuples of types that implement [`CoreExtract`].
///
/// For example, `extend_core_extract_tuple!([T16, T17])` will implement
/// [`CoreExtract`] for tuples of arity 16 and 17.
///
/// Dependency in this file must be in scope for this macro to work.
#[macro_export]
macro_rules! extend_core_extract_tuple {
    ([$($ty:ident),+]) => {
        for_tuples!(
            impl_core_extract_tuple,
            prefix = [
                T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15
            ],
            extend = [$($ty),+]
        );
    };
}

/// Tuple trait-impl generator.
///
/// Trait impl for tuples of various arities are normally
/// generated by a macro that lists every arity up to a fixed cap (axum caps at
/// 16). `for_tuples!` lets that list be built in *segments*.
///
/// For example, the default segment covers arities 0..=15, and if more are
/// ever needed, a caller can append `T16..T_any` via `extend` instead of
/// rewriting the first 16. Impl for arities already covered by the prefix
/// are never emitted to avoid duplicate trait impl.
///
/// The invoked rule receives the type list wrapped in brackets, e.g.
/// `$rule!([T0, T1, T2])`.
#[macro_export]
macro_rules! for_tuples {
    ($rule:ident, prefix = [$($p:ident),*], extend = [$($e:ident),+]) => {
        for_tuples!(@step $rule, [$($p),*], [], $($e),+);
    };

    // Recursive step: emit one impl for `prefix + acc + head`, then continue
    // with `head` moved into the accumulator and the rest of `extend` as tail.
    (@step $rule:ident, [$($p:ident),*], [$($acc:ident),*], $head:ident $(, $tail:ident)*) => {
        $rule!([$($p,)* $($acc,)* $head]);
        for_tuples!(@step $rule, [$($p),*], [$($acc,)* $head], $($tail),*);
    };

    // Base case: `extend` is exhausted, stop recursing.
    (@step $rule:ident, [$($p:ident),*], [$($acc:ident),*],) => {};
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestExtract;

    impl CoreExtract for TestExtract {
        fn extract(_core: &mut Core) -> Self {
            Self
        }
    }

    #[test]
    fn extract_tuple() {
        // (TestExtract,) must implement CoreExtract.
        fn assert_impl<T: CoreExtract>() {}
        assert_impl::<(TestExtract,)>();

        // (TestExtract, u8) must NOT implement CoreExtract: `u8` has no
        // CoreExtract impl, so the tuple impl must not apply.
        // `some_item` is only ambiguous if the tuple implements CoreExtract,
        // in which case this test fails to compile.
        trait AmbiguousIfImpl<A> {
            fn some_item() {}
        }
        impl<T: ?Sized> AmbiguousIfImpl<()> for T {}
        struct Invalid;
        impl<T: ?Sized + CoreExtract> AmbiguousIfImpl<Invalid> for T {}
        let _ = <(TestExtract, u8) as AmbiguousIfImpl<_>>::some_item;
    }
}
